### ISSUE TITLE
EntityWorld Delta property not updating

### ISSUE THREAD

**Issue by Bambofy** [thelinuxlich/artemis_CSharp#87] opened 2015-07-23 13:50 UTC
Had an issue where in the OnUpdateFrame method, calling _entityWorld.Update((long) e.Time) did not update the EntityWorld.Delta property so i could not access it in a EntityProcessingSystem.

Resolved by changing it to _entityWorld.Update() (uses internal method to calculate Delta?).

**Comment by Maximusya** [comment] 2015-07-23 14:54
What is *e* and what is *e.Time*? Might be a rounding issue.
And yes, ```entityWorld.Update()``` uses internal member to calculate Delta

**Comment by GrafSeismo** [comment] 2015-12-16 03:27
e.Time should be at least > 0 than this will work

**Comment by Maximusya** [comment] 2016-02-16 08:05
Closing this due to no feedback, "works for me", "can't reproduce" - whatever)

**Closed by Maximusya** 2016-02-16 08:05 UTC
